[package]
edition = "2024"
resolver = "3"
name = "rust_fib"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-recursion = "1.1.1"
tokio = { version = "1.52.1", features = ["full"] }
rayon = "1.12.0"
kanal = "0.1.1"

[dev-dependencies]
criterion = { version = "0.8.2", features = ["html_reports", "async_tokio"] }

[[bench]]
name = "fib_benchmark"
harness = false
